from __future__ import annotations

from argparse import ArgumentParser, Namespace, RawDescriptionHelpFormatter, ArgumentTypeError
from datetime import datetime
from jinja2 import Environment, FileSystemLoader  # type: ignore
# from pprint import pprint

import os
import sys
import json
import textwrap
import shutil

import numpy as np
import matplotlib.pyplot as plt  # type: ignore

from src_new.dante_generate_msa import write_alignment_html

DANTE_DESCRIPTION = '''
            DANTE = Da Amazing NucleoTide Exposer (Remastered)
            --------------------------------------------------
Genotyping and reporting from annotated reads generated by the remaSTR program.
The reads are filtered, clustered, and a genotype is inferred for each motif.
If a verbose option is switched on, DANTE creates a directory for each of
the annotated motifs and a summary report in HTML (report.html). Otherwise only
a table with all genotypes, confidences, and supporting information.
'''


def main() -> None:
    # mkdir -p ../../analyses/2025-09-10_nomenclature_unification/dante_agg
    # python ./dante_remastr_simple_agg_and_report.py
    #   -i ../../analyses/2025-09-10_nomenclature_unification/dante_out_simple/*/data.json
    #   -o ../../analyses/2025-09-10_nomenclature_unification/dante_agg
    start_time = datetime.now()
    args = load_arguments()

    print('DANTE_remaSTR = "Da Amazing NucleoTide Exposer" (remastered)')
    print(f'DANTE_remaSTR Starting : {start_time:%Y-%m-%d %H:%M:%S}')

    data_json = get_aggregated_json(args.input_jsons)

    # next lines are only outputing things
    os.makedirs(args.output_dir, exist_ok=True)

    print(f"Dumping data_v2.json: {datetime.now():%Y-%m-%d %H:%M:%S}")
    json_example = json.dumps(data_json, indent=2)
    with open(f"{args.output_dir}/data_v2.json", "w") as f:
        f.write(json_example)

    print(f'Writing html report: {datetime.now():%Y-%m-%d %H:%M:%S}')
    script_dir = os.path.dirname(sys.argv[0]) + "/templates"
    env = Environment(loader=FileSystemLoader([script_dir]), trim_blocks=True, lstrip_blocks=True)

    template = env.get_template("report_template2.html")
    output = template.render(data=data_json)
    with open(f"{args.output_dir}/report.html", "w") as f:
        f.write(output)

    template_static = env.get_template("report_template2_static.html")
    output_static = template_static.render(data=data_json)
    with open(f"{args.output_dir}/report_static.html", "w") as f:
        f.write(output_static)

    print(f"Creating histogram plots: {datetime.now():%Y-%m-%d %H:%M:%S}")
    create_histograms(data_json, args.output_dir)

    print(f'Copying includes: {datetime.now():%Y-%m-%d %H:%M:%S}')
    copy_includes(args.output_dir)

    os.makedirs(f"{args.output_dir}/alignments", exist_ok=True)
    for (tsv_file, json_file) in zip(args.input_tsv, args.input_jsons):
        motif = os.path.basename(tsv_file).split(".")[0]
        output_file = f"{args.output_dir}/alignments/{motif}.html"
        print(f'Writing alignment htmls: {json_file} + {tsv_file} -> {output_file}')
        write_alignment_html(json_file, tsv_file, output_file, args.male)

    # next lines assume joined tsv file
    # print(f'Writing tsv output: {datetime.now():%Y-%m-%d %H:%M:%S}')
    # variants_df = construct_dataframe(data_json, args.input_tsv, args.male)
    # variants_df.to_csv(args.output_dir + "/variants.tsv", sep='\t')

    # print(f'Writing vcf output: {datetime.now():%Y-%m-%d %H:%M:%S}')
    # write_vcf(variants_df, args.output_dir)

    end_time = datetime.now()
    print(f'DANTE_remaSTR Stopping : {end_time:%Y-%m-%d %H:%M:%S}')
    print(f'Total time of run      : {end_time - start_time}')


def get_aggregated_json(filenames: list[str]):
    with open(filenames[0], "r") as f:
        main_data = json.load(f)

    for filename in filenames[1:]:
        print(f"Loading {filename}")
        with open(filename, "r") as f:
            data = json.load(f)
        main_data["motifs"].extend(data["motifs"])

    return main_data


def copy_includes(output_dir: str) -> None:
    include_dir = os.path.dirname(sys.argv[0]) + "/includes"
    os.makedirs(f'{output_dir}/includes', exist_ok=True)
    shutil.copy2(f'{include_dir}/msa.min.gz.js',            f'{output_dir}/includes/msa.min.gz.js')
    shutil.copy2(f'{include_dir}/plotly-2.14.0.min.js',     f'{output_dir}/includes/plotly-2.14.0.min.js')
    shutil.copy2(f'{include_dir}/jquery-3.6.1.min.js',      f'{output_dir}/includes/jquery-3.6.1.min.js')
    shutil.copy2(f'{include_dir}/datatables.min.js',        f'{output_dir}/includes/datatables.min.js')
    shutil.copy2(f'{include_dir}/styles.css',               f'{output_dir}/includes/styles.css')
    shutil.copy2(f'{include_dir}/w3.css',                   f'{output_dir}/includes/w3.css')
    shutil.copy2(f'{include_dir}/jquery.dataTables.css',    f'{output_dir}/includes/jquery.dataTables.css')


def create_histograms(data: dict, output_dir: str) -> None:
    os.makedirs(f"{output_dir}/plots", exist_ok=True)
    for motif in data["motifs"]:
        motif_id = motif["motif_id"]
        for i, module in enumerate(motif["modules"]):
            if module["graph_data"][0] is None:
                continue
            output_file = f"{output_dir}/plots/{motif_id}_{i}_histogram.png"
            title = f"Histogram of read annotations for {motif_id}-{i}"
            spanning, flanking, _ = module["graph_data"][0]

            total = [x + y for x, y in zip(spanning, flanking)]
            n = max(i for i, v in enumerate(total) if v != 0)
            n = min(n + 2, len(total))
            x = np.arange(n)

            _fig, ax = plt.subplots()
            ax.bar(x, total[:n], width=0.9, label="Flanking", color='lightgrey')
            for i, height in enumerate(total[:n]):
                if flanking[i] > 0:
                    ax.text(x[i], height, str(flanking[i]), ha='center', va='bottom', color='lightgrey')

            ax.bar(x, spanning[:n], width=0.9, label="Spanning", color='C0')
            for i, height in enumerate(spanning[:n]):
                if height > 0:
                    ax.text(x[i], height, str(height), ha='center', va='bottom', color='C0')

            ax.set_ylim(top=max(total[:n]) + 2)
            ax.spines['top'].set_visible(False)
            ax.spines['right'].set_visible(False)

            nonzero_indices = [i for i, v in enumerate(total[:n]) if v > 0]
            ax.set_xticks(nonzero_indices)
            ax.set_xticklabels([str(i) for i in nonzero_indices])
            ax.set_title(title)

            ax.legend()
            plt.savefig(output_file)
            plt.close()
    return


def load_arguments() -> Namespace:
    """
    Loads and parses the arguments.
    :return: args - parsed arguments
    """
    parser = ArgumentParser(
        formatter_class=RawDescriptionHelpFormatter,
        description=textwrap.dedent(DANTE_DESCRIPTION)
    )

    options = parser.add_argument_group('Options')
    options.add_argument(
        '--input-tsv', '-r', nargs="+",
        help='Path to tsv output file from remastr tool.'
    )
    options.add_argument(
        '--input-jsons', '-j', nargs="+",
        help='Path to data.json files (possibly many) as obtained by dante_remastr_simple.'
    )
    options.add_argument(
        '--output-dir', '-o', type=str, default="dante_out",
        help='Output destination (directory). Default=./dante_out/'
    )
    options.add_argument(
        '--verbose', '-v', action='store_true',
        help='Print all the outputs. Default is to print only the result table to stdout.'
    )
    options.add_argument(
        '--male', action='store_true',
        help='Indicate that the sample is male. Process motifs from chrX/chrY as mono-allelic.'
    )
    options.add_argument(
        '--nomenclatures', '-n', type=positive_int, default=5,
        help='Number of nomenclature strings to add to reports. Default=5'
    )
    options.add_argument(
        '--cutoff-alignments', type=positive_int, default=20,
        help='How many bases to keep beyond annotated part. Default=20'
    )

    args = parser.parse_args()

    return args


def positive_int(value: str) -> int:
    try:
        int_value = int(value)
    except ValueError:
        raise ArgumentTypeError(f'Value {value} is not integer') from None
    if int_value < 0:
        raise ArgumentTypeError(f'Value {value} is negative')
    return int_value


# def test1() -> None:
#     print("kjsk")
# def load_arguments_fake() -> Namespace:
#     return Namespace(
#         output_dir='dante_out',
#         input_tsv=open("../../cache/HG002.GRCh38.remastr_output.tsv", "r"),
#         male=False,
#
#         verbose=True,
#         nomenclatures=5,
#         cutoff_alignments=20,
#     )


# %%
if __name__ == '__main__':
    main()
    # test1()
